package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'E_Fdsf'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("E_Fdsf")) {
    expectSteps {
        script {
            name = "fddd"
            scriptContent = """
                echo foo > foo.txt
                mkdir bar
                echo barfoo > bar/foo.txt
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            enabled = false
        }
    }
}
