package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'E'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("E")) {
    check(name == "e") {
        "Unexpected name: '$name'"
    }
    name = "Test"
}
