package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'XirgoCommonLib_XirgoCommonLib'
in the project with id = 'XirgoCommonLib', and delete the patch script.
*/
create(RelativeId("XirgoCommonLib"), GitVcsRoot({
    id("XirgoCommonLib_XirgoCommonLib")
    name = "XirgoCommonLib"
    url = "ssh://git@bitbucket.xirgotech.com:7999/xdm/xirgocommonlib.git"
    authMethod = uploadedKey {
        uploadedKey = "id_rsa"
    }
}))

